### PR TITLE
Add Rewe and Contentful as sponsors.

### PR DESCRIPTION
**Pull request by anselmh**
screen shot 2016-06-17 at 11 48 29

### CODE REVIEW

**Comment by drublic** [comment]
Can we maybe show them in a box or something? It looks a bit broken.

**Comment by anselmh** [comment]
What looks broken? What content exactly would you want to display in a box?

**Comment by drublic** [comment]
I thought about putting each sponsor into their own box or anything like this. We had this last year. I just think it looks a bit cleaner if you make the grid visible.

**Comment by ixisio** [comment]
@drublic I've created a container for default paragraphs and wrap partner logo's in boxes. 
@anselmh Looks okay for you?

screen shot 2016-06-20 at 09 34 42
screen shot 2016-06-20 at 09 35 00

**Comment by anselmh** [comment]
Yep, that looks better. Maybe it could get a bit more padding?

**Pull request merged**
