### PR TITLE
Add nexum partner to partners page and footer

### PR DESCRIPTION
**Pull request by ixisio**
- Add nexum partner to partners page
- Add nexum partner to Footer Partner List
- Center Ticket / Central Theme on startpage

screen shot 2016-06-28 at 10 34 48
screen shot 2016-06-28 at 10 41 01

### CODE REVIEW

**Comment by anselmh** [comment]
We can’t easily fix the contenful logo’s height in the big detail view, can we?

**Comment by anselmh** [comment]
Besides that, looks good to me.

**Comment by ixisio** [comment]
@anselmh Hmm, same height for all logos would be an option, but looks broken because each logo has a different format. IMO it looks okay for the moment..

**Comment by ixisio** [comment]
@anselmh Or you have a better option!?

**Comment by anselmh** [comment]
extending the viewBox to have the same width + height for every logo’s viewBox?

**Pull request merged**
